apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: mmg-test-notebook
spec:
  entrypoint: mmg-test-notebook
  templates:
    - name: notebook
      script:
        image: ghcr.io/diamondlightsource/magnetic-materials-workflows:0.1.0-rc3
        command:
          - jupyter-nbconvert
          - --execute
          - --stdin
          - --to
          - html
          - --output
          - notebook
          - --output-dir
          - /outputs
        source: |
          {{ .Files.Get "notebooks/mmg_test_processor.ipynb" | fromJson | toPrettyJson | nindent 10 }}
        volumeMounts:
          - name: tmpdir
            mountPath: /tmpdir
  volumeClaimTemplates:
    - metadata:
        name: tmpdir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: local-path
  arguments:
    parameters:
      - name: visitdir
        valueFrom:
          configMapKeyRef:
            name: sessionspaces
            key: data_directory
  volumes:
    - name: session
      hostPath:
        path: "{{ workflow.parameters.visitdir }}"
        type: Directory
