apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: mmg-test-python
spec:
  entrypoint: mmg-test-python
  arguments:
    parameters:
      - name: visitdir
        valueFrom:
          configMapKeyRef:
            name: sessionspaces
            key: data_directory
  volumes:
    - name: session
      hostPath:
        path: "{{ workflow.parameters.visitdir }}"
        type: Directory
  templates:
  - name: mmg-test-python
    inputs:
      parameters:
      - name: scanno
        value: 1057496
      - name: python-code
        value: | 
          print(f"Scan command: {cmd}")
    script:
      image: ghcr.io/diamondlightsource/magnetic-materials-workflows:0.1.0-rc1
      volumeMounts:
        - name: session
          mountPath: "{{ workflow.parameters.visitdir }}"
      command: ["python"]
      source: |
        import numpy as np
        import time
        import h5py
  
        filename = '{{workflow.parameters.visitdir}}/{{inputs.parameters.scanno}}.nxs'
        print(filename)
  
        with h5py.File(filename, 'r') as hdf:
          dataset = hdf['entry1/scan_command']
          cmd = dataset.asstr()[()]
        {{inputs.parameters.python-code}}
