apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: mmg-test-python
spec:
  entrypoint: mmg-test-python
  arguments:
    parameters:
      - name: visitdir
        valueFrom:
          configMapKeyRef:
            name: sessionspaces
            key: data_directory
  volumes:
    - name: session
      hostPath:
        path: "{{ workflow.parameters.visitdir }}"
        type: Directory
  templates:
  - name: mmg-test-python
    inputs:
      parameters:
      - name: scanno
        value: 1057496
      - name: python-code
        value: | 
          print(f"Scan command: {cmd}")
    script:
      image: ghcr.io/diamondlightsource/magnetic-materials-workflows:0.1.0-rc1
      volumeMounts:
        - name: session
          mountPath: "{{ workflow.parameters.visitdir }}"
      command: ["python"]
      source: |
        import numpy as np
        import matplotlib.pyplot as plt
        import babelscan
        
        from babelscan.plotting_matplotlib import set_plot_defaults
        set_plot_defaults()  # set custom matplotlib rcParams
        i16 = babelscan.instrument_from_config('i16')
  
        filename = '{{workflow.parameters.visitdir}}/{{inputs.parameters.scanno}}.nxs'
        print(filename)
        scan = i16.scan(filename)
        print(scan)
        cmd = scan('cmd')
  
        {{inputs.parameters.python-code}}
