apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: mmg-test-python
spec:
  entrypoint: mmg-test-python
  templates:
  - name: mmg-test-python
    inputs:
      parameters:
      - name: size
        value: 2000
      - name: memory
        value: 20Gi
    script:
      image: ghcr.io/diamondlightsource/magnetic-materials-workflows:0.1.0-rc1
      command: ["python"]
      source: |
        import numpy as np
        import time
        import h5py
        
        with h5py.File('1057496.nxs', 'r') as hdf:
          dataset = hdf['entry1/scan_command']
          cmd = dataset.asstr()[()]
        print(f"Scan command: {cmd}")

      source: |
          import numpy as np
          import time
          import h5py

          print('{{namespace}}')
          print('{{workflow.inputs.scanno}}')
          print('{{workflow.inputs.message}}')

          filename = '/dls/i16/data/2024/{{workflow.metadata.namespace}}/{{workflow.inputs.scanno}}.nxs'
          print(filename)

          with h5py.File(filename, 'r') as hdf:
            dataset = hdf['entry1/scan_command']
            cmd = dataset.asstr()[()]
          print(f"Scan command: {cmd}")
