apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: convert-to-dat
  labels:
    workflows.diamond.ac.uk/science-group-magnetic-materials: "true"
  annotations:
    workflows.argoproj.io/title: Convert to .dat
    workflows.argoproj.io/description: |
      Converts .nxs files to .dat.
    workflows.argoproj.io/repository: |
      "https://github.com/DiamondLightSource/magnetic-materials-workflows"
    workflows.diamond.ac.uk/parameter-schema: |
      {{- .Files.Get "schemas/convert-to-dat_param.json" | nindent 6 }}
    workflows.diamond.ac.uk/ui-schema: |
      {{- .Files.Get "schemas/convert-to-dat_ui.json" | nindent 6 }}
spec:
  entrypoint: convert-to-dat
  arguments:
    parameters:
    - name: visitdir
      valueFrom:
        configMapKeyRef:
          name: sessionspaces
          key: data_directory
  volumes:
  - name: session
    hostPath:
      path: "{{`{{ workflow.parameters.visitdir }}`}}"
      type: Directory
  templates:
  - name: convert-to-dat
    inputs:
      parameters:
      - name: scan_numbers
      - name: dat_file
      - name: all_scans
      - name: write_tiff
      - name: overwrite
    script:
      image: ghcr.io/diamondlightsource/magnetic-materials-workflows
      volumeMounts:
        - name: session
          mountPath: "{{`{{ workflow.parameters.visitdir }}`}}"
      command: ["python"]
      source: |
        import os
        import re
        import glob
        import numpy as np
        from nexus2srs import nxs2dat

        def replace_scan_number(filename: str, new_number: int) -> str:
          return re.sub(r"\d{3,}.nxs$", str(new_number)+".nxs", filename)

        datadir = "{{`{{ workflow.parameters.visitdir }}`}}"
        if not os.path.isdir(datadir):
          raise ValueError("data directory not found")

        scan_numbers_string = "{{`{{inputs.parameters.scan_numbers}}`}}"
        dat_file = "{{`{{inputs.parameters.dat_file}}`}}"
        all_scans = True if "{{`{{inputs.parameters.all_scans}}`}}".lower() == "true" else False
        write_tiff = True if "{{`{{inputs.parameters.write_tiff}}`}}".lower() == "true" else False
        overwrite = True if "{{`{{inputs.parameters.overwrite}}`}}".lower() == "true" else False

        nxs_files = glob.glob(os.path.join(datadir, "*.nxs"))
        if len(nxs_files) == 0:
          raise FileNotFoundError("No .nxs files found")
        
        base_fname = nxs_files[0]

        if all_scans:
          scans = nxs_files
        elif "-" in scan_numbers_string:
          start, stop = scan_numbers_string.split("-")
          scan_numbers = np.arange(int(start), int(stop) + 1)
          scans = (replace_scan_number(base_fname, n) for n in scan_numbers)
        else:
          scan_numbers = np.fromstring(scan_numbers_string, dtype=int, sep=',')
          scans = (replace_scan_number(base_fname, n) for n in scan_numbers)
        
        for scan in scans:
          if not os.path.exists(scan):
            raise FileNotFoundError(f"file not found: {scan}")
          nexs2dat(scan, dat_file, write_tiff, overwrite)

