apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: mmg-test-notebook
spec:
  entrypoint: mmg-test-notebook
  arguments:
    parameters:
      - name: visitdir
        valueFrom:
          configMapKeyRef:
            name: sessionspaces
            key: data_directory
      - name: inpath
        value: ""
      - name: outpath
        value: ""
  volumes:
    - name: session
      hostPath:
        path: "{{`{{ workflow.parameters.visitdir }}`}}"
        type: Directory
  volumeClaimTemplates:
    - metadata:
        name: tmp
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: netapp

  templates:
    - name: convert-notebook
      script:
        image: ghcr.io/diamondlightsource/magnetic-materials-workflows:0.2.0-rc1
        command: [ bash ]
        source: |
          # mount-files
          echo '{{ .Files.Get "notebooks/mmg_processor.ipynb" | b64enc }}' | base64 -d > /tmp/notebook.ipynb
          # create matplotlib config dir
          mkdir -p /tmp/mpl
          export MPLCONFIGDIR=/tmp/mpl
          # run notebook
          python -m papermill /tmp/notebook.ipynb /tmp/notebook.ipynb \
            -p datadir "{{`{{ workflow.parameters.visitdir }}`}}" \
            -p inpath "{{`{{ workflow.parameters.inpath }}`}}" \
            -p outpath "{{`{{ workflow.parameters.outpath }}`}}"
          python -m nbconvert --execute --allow-errors --to html --output notebook --output-dir /tmp /tmp/notebook.ipynb
        volumeMounts:
          - name: tmp
            mountPath: /tmp
          - name: session
            mountPath: "{{`{{ workflow.parameters.visitdir }}`}}"
      outputs:
        artifacts:
          - name: notebook
            path: /tmp/notebook.html
            archive:
              none: {}
          - name: plot
            path: /tmp/output.png
            archive:
              none: {}
          - name: dat-file
            path: /tmp/nexus.txt
            archive:
              none: {}
    - name: mmg-test-notebook
      dag:
        tasks:
          - name: convert-notebook
            template: convert-notebook
