apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: mmg-test-python
spec:
  entrypoint: mmg-test-python
  arguments:
    parameters:
      - name: visitdir
        valueFrom:
          configMapKeyRef:
            name: sessionspaces
            key: data_directory
  volumes:
    - name: session
      hostPath:
        path: "{{`{{ workflow.parameters.visitdir }}`}}"
        type: Directory
  templates:
  - name: mmg-test-python
    inputs:
      parameters:
      - name: scan-no
        value: 26804
      - name: python-code
        value: |
          print(f"Scan command: {cmd}")
    script:
      image: ghcr.io/diamondlightsource/magnetic-materials-workflows:0.1.0-rc3
      volumeMounts:
        - name: session
          mountPath: "{{`{{ workflow.parameters.visitdir }}`}}"
      command: ["python"]
      source: |
        import numpy as np
        import hdfmap

        filename = '{{`{{workflow.parameters.visitdir}}`}}/i10-1-{{`{{inputs.parameters.scan-no}}`}}.nxs'
        print(filename)
        scan = hdfmap.NexusLoader(filename)
        print(scan)
        cmd = scan('scan_command')

        {{`{{inputs.parameters.python-code}}`}}